# Generated by Django 2.0.3 on 2018-03-19 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_date_of_admission', models.DateTimeField(verbose_name='date published')),
                ('patient_problem', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='belongs_to',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discharge_time', models.DateTimeField()),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='consults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allot_room', models.BooleanField(default=True)),
                ('prescription', models.CharField(max_length=200)),
                ('appointment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.appointment')),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=50)),
                ('office_no', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='doctor_phone_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=200)),
                ('doctor_s_time', models.TimeField(blank=True)),
                ('doctor_e_time', models.TimeField(blank=True)),
                ('doctor_date_of_joining', models.DateField(blank=True)),
                ('doctor_availability', models.BooleanField(default=True)),
                ('doctor_degree', models.CharField(max_length=10)),
                ('doctor_salary', models.IntegerField()),
                ('doctor_consultation_fee', models.IntegerField()),
                ('doctor_login', models.CharField(default='secret', max_length=20)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.department')),
            ],
        ),
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=1)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='maintains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.bill')),
            ],
        ),
        migrations.CreateModel(
            name='patient_phone_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_city_name', models.CharField(max_length=200)),
                ('patient_house_no', models.IntegerField()),
                ('patient_street_no', models.IntegerField()),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receptionist_name', models.CharField(max_length=200)),
                ('receptionist_date_of_joining', models.DateTimeField(verbose_name='date published')),
                ('receptionist_salary', models.IntegerField()),
                ('receptionist_login', models.CharField(default='secret', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(default=200)),
            ],
        ),
        migrations.AddField(
            model_name='patient_phone_number',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.patients'),
        ),
        migrations.AddField(
            model_name='maintains',
            name='receptionist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.receptionist'),
        ),
        migrations.AddField(
            model_name='doctor_phone_number',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.doctors'),
        ),
        migrations.AddField(
            model_name='consults',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.doctors'),
        ),
        migrations.AddField(
            model_name='belongs_to',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.department'),
        ),
        migrations.AddField(
            model_name='belongs_to',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.doctors'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.patients'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='receptionist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manageHospital.receptionist'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manageHospital.room'),
        ),
    ]
