# Generated by Django 2.0.3 on 2018-03-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_city_name', models.CharField(max_length=200)),
                ('patient_house_no', models.IntegerField()),
                ('patient_street_no', models.IntegerField()),
                ('patient_age', models.IntegerField()),
                ('patient_date_of_admission', models.DateTimeField(verbose_name='date published')),
                ('patient_gender', models.CharField(max_length=200)),
                ('patient_problem', models.CharField(max_length=500)),
            ],
        ),
    ]
