# Generated by Django 2.0.3 on 2018-03-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageHospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='treated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bill',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient_date_of_admission',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='receptionist',
            name='receptionist_date_of_joining',
            field=models.DateTimeField(),
        ),
    ]
