# Generated by Django 2.0.3 on 2018-03-19 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageHospital', '0002_auto_20180319_0421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctors',
            old_name='doc_id',
            new_name='id',
        ),
    ]
