# Generated by Django 2.0.3 on 2018-03-19 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageHospital', '0004_auto_20180319_0422'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(default=200)),
            ],
        ),
        migrations.AddField(
            model_name='consults',
            name='allot_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctors',
            name='doctor_charge',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='room_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='manageHospital.room'),
            preserve_default=False,
        ),
    ]
