# Generated by Django 2.0.3 on 2018-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageHospital', '0006_auto_20180319_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(default=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='consults',
            name='allot_room',
        ),
    ]
