# Generated by Django 2.0.3 on 2018-03-19 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageHospital', '0007_auto_20180319_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manageHospital.room'),
        ),
        migrations.AddField(
            model_name='consults',
            name='allot_room',
            field=models.BooleanField(default=False),
        ),
    ]
