# Generated by Django 2.0.3 on 2018-03-19 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manageHospital', '0011_auto_20180319_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manageHospital.room'),
        ),
    ]
